version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - MIX_ENV=dev
      - IN_DOCKER=true
      - PORT=4000
      - SECRET_KEY_BASE=dev_secret_key_base
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - deps:/app/deps
      - build:/app/_build
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev_network
    command: >
      sh -c '
        while ! pg_isready -h db -p 5432 -U postgres; do
          echo "Waiting for database..."
          sleep 1
        done
        echo "Database is ready!"
        mix deps.get
        mix ecto.setup
        mix phx.server
      '
    stdin_open: true
    tty: true

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=token_manager_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - dev_network

volumes:
  postgres_dev_data:
  deps:
  build:

networks:
  dev_network:
    driver: bridge