FROM hexpm/elixir:1.15.7-erlang-26.2.1-alpine-3.19.1

# Install build dependencies and development tools
RUN apk add --no-cache build-base git inotify-tools postgresql-client

# Install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /app

# Set environment variables
ENV MIX_ENV=dev \
    PORT=4000

# Default command to start Phoenix
CMD ["mix", "phx.server"]